# Generated by Django 4.2.3 on 2023-08-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsmodel',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
